### ISSUE TITLE
Problème sur Mise à jour 9.0.0 sur HAOS 

### ISSUE THREAD

**Issue by fredarro** [fmartinou/teleinfo2mqtt#68]
Voici le message que j'obtiens
```
/home/node/app/config/index.js:71
        config.tempoEnabled = overrideObject.TEMPO_ENABLED.toLowerCase() === 'true';
                                                           ^

TypeError: overrideObject.TEMPO_ENABLED.toLowerCase is not a function
    at overrideConfiguration (/home/node/app/config/index.js:71:60)
    at Object.<anonymous> (/home/node/app/config/index.js:88:5)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/node/app/index.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)

Node.js v18.18.2
```

**Comment by fmartinou** [comment]
Arf.

Je corrige asap.
